#!/bin/bash
#===============================================================================
#
#          FILE: commit-msg
#
#         USAGE: ./commit-msg commit_file
#
#   DESCRIPTION: Validates whatever a commit follows the Conventional Commit Guidelines
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: ---, 
#  ORGANIZATION: ---
#       CREATED: 09/27/2021 01:24:48 AM
#      REVISION: 2021-10-29 15:11
#===============================================================================
set -o nounset

function main(){
  __TEMP=$(cat $1)
  COMMIT_MSG=$(awk 'NR==1' $1)
  CONVENTIONAL_REGEX="^(?:perf|build|test|refactor|feat|ci|fix|docs|chore|style)!?(?:\([\w\s]+\))?:\s[\s\d\w&]+(?!\.)$"
  IGNORE_FLAG="^\!{2}" 

  [[ $COMMIT_MSG =~ $IGNORE_FLAG ]] && echo "${__TEMP:2}" > $1 && echo "IGNORING CONVENTIONAL COMMIT RULES..." && exit 0
  [[ -z $(echo $COMMIT_MSG | grep -P $CONVENTIONAL_REGEX ) ]] && saveBackup $1 && conventionalError
  [[ ${#COMMIT_MSG} -gt 72 ]] && saveBackup $1 && conventionalError
  exit 0;
}

function conventionalError() {
  echo " ------------------------------------------------------ "
  echo " | PLEASE FOLLOW THE CONVENTIONAL COMMIT GUIDELINES   | "
  echo " |                                                    | "
  echo " | 1) Start with -> refactor | feat | ci | fix | docs | "
  echo " |    chore | style | test | perf | build             | "
  echo " |                                                    | "
  echo " | 2) Add an optional \`(scope)\` after rule #1         | "
  echo " |                                                    | "
  echo " | 3) The title should contain less than 73 characters| "
  echo " |                                                    | "
  echo " | 4) Add a short description                         | "
  echo " |                                                    | "
  echo " | 5) You could add a body and footer if u want       | "
  echo " ------------------------------------------------------ "
  echo ""
  echo "Start the commit message with !! to ignore all the rules. Note: The !! will be automatically removed"
  echo ""
  echo "Type \`git commit\` and fix the previous commit message ~"
  exit 1;
}

function saveBackup() {
  CLOG=/var/run/user/$UID/last_commit.log
  [[ -e  $CLOG ]] && rm $CLOG
  cp $1 /var/run/user/$UID/last_commit.log 
} > /dev/null

main $@
