#!/bin/bash
#===============================================================================
#
#          FILE: prepare-commit-msg
#
#         USAGE: ./prepare-commit-msg
#
#   DESCRIPTION: ---
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: ---, 
#  ORGANIZATION: ---
#       CREATED: 09/27/2021 01:24:48 AM
#      REVISION:  2021-10-29 15:24
#===============================================================================
set -o nounset

BACKUP=/var/run/user/$UID/last_commit.log
[[ -e  $BACKUP ]] && [[ -z $(awk 'NR==1' $BACKUP) ]] && rm $BACKUP
[[ -e  $BACKUP ]] && cat $BACKUP > $1 && rm $BACKUP

exit 0
